# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTI5ODNkMzJhM2U4MTEzOWUyMDVhZDE4YzFkZmRjZWNjYjhlZDVlMDNiYWE1ZDM1MTU4Y2QwNDYyZTgyYzIxMDM3NzJhNGYwNWVmYWYwZWU2Y2E4Njg4NjliNTkxYTg5NWFiOGMzZTg0ODczNDdlMDlkNGE2NzUwMjYzMmE3Yzg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
